BELA NEGARA 
1. Setiap warga negara memiliki kewajiban yang sama dalam masalah pembelaan negara. Hal tersebut merupakan wujud kecintaan seorang warga negara pada tanah air yang sudah memberikan kehidupan padanya. Hal ini terjadi sejak seseorang lahir, tumbuh dewasa serta dalam upayanya mencari penghidupan. Dalam pelaksanaan pembelaan negara tidak identik dengan angkat senjata, namun dapat dilakukan melalui peningkatan rasa nasionalisme yang merupakan rangkaian kecintaan dan kesadaran dalam proses berkehidupan dalam negara dan bangsa. Hal tersebut dapat diwujudkan melalui empati dan peduli terhadap sesama, sebagaimana dalam KnowledegeCapture dengan judul: “Gotong Royong: Rasa dari ASN, Asa untuk Bangsa Indonesia” oleh Mila Mumpun, Widyaiswara Balai Diklat Kepemimpinan.
2. Pegawai Negeri sebagai unsur aparatur yang bertugas untuk memberikan pelayanan kepada masyarakat secara profesional, jujur, adil, dan merata dalam penyelenggaraan tugas negara, pemerintahan, dan pembangunan. Pegawai Negeri Sipil juga mempunyai kewajiban untuk memberikan contoh yang baik dalam mentaati dan melaksanakan segala peraturan perundang-undangan yang berlaku
3. Menurut Suyanto (2009), definisi Pendidikan Karakter adalah cara berpikir dan berperilaku yang menjadi ciri khas tiap individu untuk hidup dan bekerja sama, baik dalam lingkup keluarga, masyarakat, bangsa, maupun negara. Sementara itu Thomas Lickona menganggap Pendidikan Karakter sebagai suatu usaha yang disengaja untuk membantu seseorang sehingga ia dapat memahami, memperhatikan, dan melakukan nilai-nilai etika yang inti. Karakter yang baik didukung oleh pengetahuan tentang kebaikan, keinginan untuk berbuat baik dan tindakan melakukan perbuatan kebaikan.
4. Inovasi merupakan sesuatu yang baru dan belum ada secara umum.  Inovasi ini sendiri sangat identik dengan anak muda. Sebab jiwa muda masih menyimpan banyak energi dan pemikiran. Dengan begitu, banyak hal baru dan unik yang lahir dari para pemuda. Di masa sekarang ini para pemuda ini lebih dikenal dengan yang namanya generasi milenial. Adapun pengertian inovasi menurut beberapa ahli yaitu sebagai berikut:
Menurut Nurdin (2016) Pengertian inovasi menurut Nurdin yaitu sesuatu yang baru, yang dikenalkan dan dilakukan praktik atau proses baru (baik barang ataupun layanan) atau bisa juga sesuatu yang baru namun hasil adopsi dari organisasi lain.
Menurut Sa’ud (2014) Kemudian menurut Sa’ud, inovasi adalah pilihan kreatif, pengaturan, serta seperangkat manusia dengan sumber-sumber material baru , dan juga menggunakan cara-cara yang unik guna menghasilkan peningkatan atas pencapaian yang telah menjadi tujuan sebelumnya.
KARAKTERISTIK 
5. Kehidupan sehari- hari diwarnai dengan berbagai keberagaman. Begitu pula dalam kesatuan atas syarat interaksi sosial masyarakat yang terdiri dari masing-masing individu dan kelompok dengan karakter yang beragam. Karakter yang melekat tentunya berbeda-beda antara individu yang satu dengan individu lainnya. Dalam berbagai kajian, karakter dimaknai dengan pemaknaan yang luas.
Namun yang pasti, jikalau dilihat dari segi etimologi, istilah karakter diserap dari bahasa Latin character, yang meliputi sejumlah makna antara lain yaitu watak, sifat bawaan, kepribadian, akhlak, budi pekerti serta sifat-sifat yang berkaitan dengan kejiwaan.